#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 2.4.{build}.0
os: Visual Studio 2015
install:
    - git clone https://github.com/narrieta/DscResource.Tests -b narrieta-pscore
    - ps: Import-Module -Name .\Tests\TestHelpers\WMF5Dot1Installation.psm1 -Force
    - ps: Install-Wmf5Dot1
    - ps: Start-Sleep 5
    - ps: Restart-Computer -Force
    - ps: Start-Sleep 5
    - ps: Write-Verbose -Message "Returned after restart with PSVersion $($PSVersionTable.PSVersion)" -Verbose
    - ps: if ($PSVersionTable.PSVersion -lt [Version] '5.1')
        {
            throw 'WMF 5.1 install failed'
        }
    - ps: Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
    - ps: Import-Module -Name .\Tests\TestHelpers\PSCoreInstallation.psm1
    - ps: Invoke-AppveyorInstallTask
    - ps: Install-PowerShellCore
 
#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        #$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
        Invoke-AppveyorTestScriptTask -CodeCoverage -CodeCovIo
        #$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# scripts to run before deployment
deploy_script:
    - ps: |
        Invoke-AppveyorAfterTestTask
